language: python
sudo: required
python:
  - "2.7.9"
env:
  - DJANGO_VERSION=1.4 DJANGO_SETTINGS_MODULE="almvotos.settings"
services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install MySQL-python
  - pip install rsa  
before_script:
  - mysql -e 'CREATE DATABASE votaciones_splc;'
  - cd project/AlmacenamientoVotos
  - python manage.py syncdb --noinput
  - cd almvotes
script:
  - py.test tests.py