language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8.0
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
before_script:
  - cd project/AlmacenamientoVotos/almvotes
script:
  - python tests.py
addons:
  - mariadb: "10.0"