language: python
sudo: required
python:
  - "2.7.9"
env:
  - DJANGO_VERSION=1.8 DJANGO_SETTINGS_MODULE="almvotos.settings"
services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install MySQL-python
  - pip install rsa  

before_install:
  - mysql -e 'DROP DATABASE IF EXISTS votaciones_splc'
  - mysql -e 'CREATE DATABASE votaciones_splc;'
  - mysql -u root --default-character-set=utf8 votaciones_splc < scripts/script_create_votaciones_splc.sql
  - mysql -u root --default-character-set=utf8 votaciones_splc < scripts/script_populate_votaciones_splc.sql

before_script:
  - cd project/AlmacenamientoVotos
  - python manage.py syncdb
  - cd almvotes

script:
  - py.test tests.py
