language: python
sudo: required
python:
  - "2.7.9"
env:
  - DJANGO_VERSION=1.8 DJANGO_SETTINGS_MODULE="almvotos.settings"

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install MySQL-python
  - pip install rsa
  - pip install django-fernet-fields
before_script:
  - mysql -e 'CREATE DATABASE votaciones_splc;'
  - cd project/AlmacenamientoVotos
  - python manage.py syncdb --noinput
  - cd almvotes
script:
  - py.test tests.py

addons:
  - mariadb: "10.0.31"